Repository BHoM/Revit_Toolkit, pull requests merged in 2019-10, with the labels that each got.

#383 Pull ISurface Implementation
  Engine_Revit_UI/Query/BuiltInCategories.cs
  Engine_Revit_UI/Query/RevitTypes.cs
Labels: type:feature

#401 Prevent from attempt to push analytical panels
  Adapter_Revit_UI/Create/Create.cs
Labels: discipline: Other, type:bug

#388 Null check for familyLibrary in CategoryNames query method
  Engine_Revit_UI/Convert/Geometry/ToRevit/Curve.cs
  Revit_Engine/Query/CategoryNames.cs
Labels: size:S, type:bug

#389 Add posibility to place modelInstance Two-levelbased
  Engine_Revit_UI/Compute/Warnings.cs
  Engine_Revit_UI/Convert/Revit/ToRevit/Element.cs
Labels: type:feature

#412 AssemblyInfo Updated
  Adapter_Revit_UI/Properties/AssemblyInfo.cs
  Engine_Revit_UI/Properties/AssemblyInfo.cs
  Revit_Adapter/Properties/AssemblyInfo.cs
  Revit_Engine/_Properties/AssemblyInfo.cs
  Revit_UI/Properties/AssemblyInfo.cs
  Revit_oM/_Properties/AssemblyInfo.cs
Labels: type:compliance

#417 Updating default configurations for debug and release
  Revit_Toolkit.sln
Labels: severity:critical, type:bug

#420 Building Pull Bug
  Engine_Revit_UI/Convert/Environment/ToBHoM/Building.cs
  Engine_Revit_UI/Convert/Environment/ToBHoM/Space.cs
  Engine_Revit_UI/Engine_Revit_UI.csproj
Labels: type:bug
