Repository BHoM/Revit_Toolkit, pull requests merged in 2019-06, with the labels that each got.

#294 Revit_Toolkit-Issue287-FamilySymbolOfStructuralFramingBug
  Engine_Revit_UI/Convert/Structure/ToRevit/FamilyInstance.cs
Labels: severity:critical, size:XS, status:do-not-merge, type:bug

#321 Revit_Toolkit: Update to fragments
  Engine_Revit_UI/Convert/Environment/ToBHoM/Panel.cs
  Revit_Engine/Create/Elements/Panel.cs
Labels: size:XS

#334 Update Profile.cs to fix channel section pull
  Engine_Revit_UI/Convert/Structure/ToBHoM/Profile.cs
Labels: type:bug
