Repository BHoM/Revit_Toolkit, pull requests merged in 2020-12, with the labels that each got.

#919 All references set to copy local == false
  Revit_Engine/Revit_Engine.csproj
  Revit_oM/Revit_oM.csproj
Labels: type:compliance

#921 Removal of CableTrayMaterial to match oM changes
  Revit_Core_Engine/Query/CableTraySectionProperty.cs
Labels: type:feature

#915 Ceiling pattern bugs fixed
  Revit_Core_Engine/Query/CeilingPattern.cs
Labels: type:bug

#929 MEP folder created for converts and relevant files migrated to it
  Revit_Core_Engine/Convert/MEP/FromRevit/CableTray.cs
  Revit_Core_Engine/Convert/MEP/FromRevit/Duct.cs
  Revit_Core_Engine/Convert/MEP/FromRevit/Pipe.cs
  Revit_Core_Engine/Convert/MEP/FromRevit/Wire.cs
  Revit_Core_Engine/Convert/MEP/ToRevit/CableTray.cs
  Revit_Core_Engine/Convert/MEP/ToRevit/Duct.cs
  Revit_Core_Engine/Convert/MEP/ToRevit/ElementType.cs
  Revit_Core_Engine/Convert/MEP/ToRevit/Pipe.cs
  Revit_Core_Engine/Revit_Core_Engine.csproj
Labels: type:compliance

#932 ToRevit nurbs curve convert fixed to return an approximate polyline instead of a distorted hermite spline
  Revit_Core_Engine/Convert/Geometry/ToRevit/CurveList.cs
Labels: type:bug

#938 MEP element location curve query fixed
  Revit_Core_Engine/Query/LocationCurve.cs
Labels: type:bug
