Repository BHoM/Revit_Toolkit, pull requests merged in 2020-10, with the labels that each got.

#874 Align to namespace change in Socket Toolkit
  Revit_Adapter/RevitAdapter.cs
  Revit_Core_Adapter/Listener/RevitListener.cs
Labels: type:compliance

#877 Aligning with changes to ShapeProfiles
  Revit_Core_Engine/Convert/FromRevit.cs
  Revit_Core_Engine/Convert/Structure/FromRevit/Bars.cs
  Revit_Core_Engine/Convert/Structure/FromRevit/Profile.cs
  Revit_Core_Engine/Query/BuiltInCategories.cs
  Revit_Core_Engine/Query/DuctSectionProfile.cs
  Revit_Core_Engine/Query/FramingElementProperty.cs
  Revit_Core_Engine/Query/PipeSectionProperty.cs
  Revit_Core_Engine/Query/Profile.cs
  Revit_Core_Engine/Revit_Core_Engine.csproj
Labels: type:external-api-changes

#879 Move towards using ceiling tiles for ceilings
  Revit_Core_Engine/Convert/Architecture/FromRevit/Ceiling.cs
Labels: type:feature

#886 Remove reference to AdapterIdName in the constructor
  Revit_Core_Adapter/RevitListenerAdapter.cs
  Revit_Engine/Convert/Aliases.cs
Labels: severity:critical, type:external-api-changes
