Repository BHoM/Revit_Toolkit, pull requests merged in 2020-09, with the labels that each got.

#829 Aligning with changes to panel creates
  Revit_Core_Engine/Convert/Structure/FromRevit/Panels.cs
Labels: type:external-api-changes

#838 BH.Revit.Engine.Core.Query.Outlines renamed to AnalyticalOutlines
  Revit_Core_Engine/Convert/Structure/FromRevit/Panels.cs
  Revit_Core_Engine/Query/AnalyticalOutlines.cs
  Revit_Core_Engine/Revit_Core_Engine.csproj
Labels: type:compliance

#839 Revit => BHoM freeform profile convert bugs fixed
  Revit_Core_Engine/Convert/Structure/FromRevit/Profile.cs
Labels: type:bug

#851 Bug setting wrong elevation to newly created walls fixed
  Revit_Core_Engine/Convert/Physical/ToRevit/Wall.cs
Labels: type:bug

#857 Readme updated to reflect support for Revit 2021
  README.md
Labels: type:documentation
