Repository BHoM/Revit_Toolkit, pull requests merged in 2020-07, with the labels that each got.

#780 Pulling of geometry enabled for DetailItems
  Revit_Core_Engine/Query/GeometryPrimitives.cs
Labels: type:bug

#785 Backslashes changed to slashes in descriptions
  Revit_Engine/Query/DefaultParameterSettings.cs
Labels: type:documentation

#787 Pulling hidden parameters enabled when pulled Revit element does not expose any public ones
  Revit_Core_Engine/Modify/CopyParameters.cs
Labels: type:feature

#782 Irrelevant warnings and errors stopped from being thrown on update
  Revit_Core_Engine/Modify/SetLocation.cs
  Revit_Core_Engine/Modify/SetType.cs
Labels: type:bug

#791 Added ability to get identifier and type params using GetRevitParamValue
  Revit_Engine/Query/GetRevitParameterValue.cs
Labels: type:feature

#804 PlanarSurfaceDictionary method replaced with PanelSurfaces in CeilingPattern query
  Revit_Core_Engine/Query/CeilingPattern.cs
Labels: type:compliance

#803 PanelSurfaces and OpeningSurface methods introduced to BEnv panel converts from Revit
  Revit_Core_Engine/Convert/Environment/FromRevit/Panel.cs
Labels: type:compliance

#806 SurfacePropertyFromRevit fixed not to crash on Revit panel types without any layers
  Revit_Core_Engine/Convert/Structure/FromRevit/SurfaceProperty.cs
Labels: type:bug

#814 Ceiling pattern query stopped from throwing red error when there is no pattern on Revit ceiling
  Revit_Core_Engine/Query/CeilingPattern.cs
Labels: type:bug

#816 BHoM => Revit conversion failure warning changed to error
  Revit_Core_Engine/Compute/Errors.cs
  Revit_Core_Engine/Compute/Warnings.cs
  Revit_Core_Engine/Convert/ToRevit.cs
Labels: type:bug

#817 Pull fixed not to unselect Revit elements in the process
  Revit_Core_Adapter/CRUD/Read.cs
Labels: type:bug
