Repository BHoM/Revit_Toolkit, pull requests merged in 2020-11, with the labels that each got.

#891 CustomData removed
  Revit_Core_Adapter/CRUD/Read.cs
  Revit_Core_Adapter/RevitListenerAdapter.cs
  Revit_Core_Engine/Compute/Warnings.cs
  Revit_Core_Engine/Convert/Revit/FromRevit/BHoMObject.cs
  Revit_Core_Engine/Convert/Revit/FromRevit/ViewPlan.cs
  Revit_Core_Engine/Convert/Revit/ToRevit/Sheet.cs
  Revit_Core_Engine/Convert/Revit/ToRevit/ViewPlan.cs
  Revit_Core_Engine/Convert/Revit/ToRevit/Viewport.cs
  Revit_Core_Engine/Convert/ToRevit.cs
  Revit_Core_Engine/Modify/CopyCharacteristics.cs
  Revit_Core_Engine/Query/Identifiers.cs
  Revit_Core_Engine/Revit_Core_Engine.csproj
  Revit_Engine/Create/Elements/DraftingInstance.cs
  Revit_Engine/Create/Elements/ModelInstance.cs
  Revit_Engine/Create/Elements/Sheet.cs
  Revit_Engine/Create/Elements/ViewPlan.cs
  Revit_Engine/Create/Elements/Viewport.cs
  Revit_Engine/Create/Properties/InstanceProperties.cs
  Revit_Engine/Create/Requests/FilterTypesOfFamily.cs
  Revit_Engine/Query/CategoryName.cs
  Revit_Engine/Query/CustomDataValue.cs
  Revit_Engine/Query/Family.cs
  Revit_Engine/Query/FamilyPlacementTypeName.cs
  Revit_Engine/Query/GetRevitIdentifiers.cs
  Revit_Engine/Query/RevitEdges.cs
  Revit_Engine/Query/RevitMeshes.cs
  Revit_Engine/Query/RevitSurfaces.cs
  Revit_Engine/Revit_Engine.csproj
  Revit_oM/Config/PullGeometryConfig.cs
  Revit_oM/Config/PullRepresentationConfig.cs
  Revit_oM/Config/RevitPullConfig.cs
  Revit_oM/Elements/IView.cs
  Revit_oM/Elements/Sheet.cs
  Revit_oM/Elements/ViewPlan.cs
  Revit_oM/Elements/Viewport.cs
  Revit_oM/Misc/RevitGeometry.cs
  Revit_oM/Misc/RevitRepresentation.cs
  Revit_oM/Parameters/RevitIdentifiers.cs
  Revit_oM/Properties/InstanceProperties.cs
  Revit_oM/Revit_oM.csproj
Labels: type:bug, type:compliance

#893 PreviousInputNamesAttributes added to Sheet and ViewPlan
  Revit_Engine/Create/Elements/Sheet.cs
  Revit_Engine/Create/Elements/ViewPlan.cs
Labels: type:compliance

#901 Replace Building create method with object creation
  Revit_Core_Engine/Convert/Environment/FromRevit/Building.cs
Labels: type:compliance

#904 Creation of FreeFormProfile changed from constructor to Create method
  Revit_Core_Engine/Convert/Structure/FromRevit/Profile.cs
Labels: type:bug

#909 BHoM method loading made more eager
  Revit_Core_Adapter/Listener/RevitListener.cs
Labels: type:bug
