Repository BHoM/Revit_Toolkit, pull requests merged in 2020-02, with the labels that each got.

#550 Remove duplicated code calling
  Engine_Revit_UI/Convert/Architecture/ToBHoM/Room.cs
Labels: type:bug

#555 FilterByType method deprecated
  Revit_Engine/Query/FilterByType.cs
  Revit_Engine/Revit_Engine.csproj
Labels: size:XS, type:compliance

#556 SelectionRequest moved to Data_oM
  Engine_Revit_UI/Query/ElementIds/ElementIds.cs
  Revit_oM/Requests/SelectionRequest.cs
  Revit_oM/Revit_oM.csproj
Labels: size:XS, type:feature

#551 Boilerplate ToBHoMConstruction removed
  Engine_Revit_UI/Convert/Physical/ToBHoM/Construction.cs
  Engine_Revit_UI/Convert/ToBHoM.cs
Labels: size:S, type:bug, type:feature

#549 Update IElement references with the Dimensional_oM
  Adapter_Revit_UI/Adapter_Revit_UI.csproj
  Engine_Revit_UI/Engine_Revit_UI.csproj
  Revit_Engine/Revit_Engine.csproj
  Revit_oM/Revit_oM.csproj
Labels: type:compliance

#567 Pull of Energy Analysis model refactored
  Engine_Revit_UI/Convert/Environment/ToBHoM/Building.cs
  Engine_Revit_UI/Convert/Environment/ToBHoM/EnergyAnalysisModel.cs
  Engine_Revit_UI/Convert/ToBHoM.cs
  Engine_Revit_UI/Engine_Revit_UI.csproj
  Engine_Revit_UI/Query/ElementIds/ElementIds.cs
  Engine_Revit_UI/Query/ElementIds/ElementIdsEnergyAnalysisModel.cs
  Revit_Engine/Query/Discipline.cs
  Revit_oM/Requests/EnergyAnalysisModelRequest.cs
  Revit_oM/Revit_oM.csproj
Labels: size:M, type:compliance

#569 BH.Engine.Adapters.Revit.Query.IsZero(double) deprecated
  Revit_Engine/Query/IsZero.cs
Labels: size:XS, type:compliance

#568 Conversion of Geometry objects to Environment.Panels disallowed
  Engine_Revit_UI/Convert/ToBHoM.cs
  Engine_Revit_UI/Engine_Revit_UI.csproj
  Engine_Revit_UI/Query/IsHorizontal.cs
  Engine_Revit_UI/Query/IsVertical.cs
  Engine_Revit_UI/Query/Panels.cs
  Engine_Revit_UI/Query/TopPlanarFace.cs
Labels: size:S, type:compliance

#571 BH.UI.Revit.Engine.Modify.Append deleted
  Engine_Revit_UI/Engine_Revit_UI.csproj
  Engine_Revit_UI/Modify/Append.cs
Labels: size:XS, type:compliance
