Repository BHoM/Revit_Toolkit, pull requests merged in 2020-03, with the labels that each got.

#588 Unused files and legacy methods removed
  Engine_Revit_UI/Convert/Revit/ToBHoM/Material.cs
  Engine_Revit_UI/Convert/Revit/ToRevit/Material.cs
  Engine_Revit_UI/Convert/Structure/ToBHoM/PanelPlanar.cs
  Engine_Revit_UI/Engine_Revit_UI.csproj
  Engine_Revit_UI/Query/ICustomData.cs
  Engine_Revit_UI/Query/IntegerValue.cs
  Engine_Revit_UI/Query/SelectionBuiltInCategories.cs
  Revit_Engine/Convert/AdapterID.cs
  Revit_Engine/Properties/AssemblyInfo.cs
  Revit_Engine/Revit_Engine.csproj
  Revit_oM/Settings/UpdatePropertySettings.cs
Labels: size:S

#592 Support for disjoint FilledRegions added
  Engine_Revit_UI/Convert/Revit/ToBHoM/DraftingInstance.cs
  Engine_Revit_UI/Convert/Revit/ToRevit/Element.cs
  Revit_Engine/Create/Elements/DraftingInstance.cs
Labels: size:S, type:bug

#599 Update CI Files
  .ci/check-all-depandants.yml
  .ci/check-core.yml
  .ci/check-installer.yml
  .ci/run-compliance-tests.yml
Labels: type:compliance

#625 README updated
  README.md
Labels: type:documentation

#626 Readme updated, legacy file deleted from root folder
  Build.xml
  README.md
Labels: type:compliance, type:documentation

#646 Public static methods turned into extension methods
  Engine_Revit_UI/Modify/UpdateMaterialProperties.cs
  Engine_Revit_UI/Query/EnergyAnalysisElementName.cs
  Engine_Revit_UI/Query/HighElevation.cs
  Engine_Revit_UI/Query/HighLevel.cs
  Engine_Revit_UI/Query/HostedBuildingElements.cs
  Engine_Revit_UI/Query/IsVerticalNonLinearCurve.cs
  Engine_Revit_UI/Query/LowElevation.cs
  Engine_Revit_UI/Query/LowLevel.cs
  Engine_Revit_UI/Query/Name.cs
  Engine_Revit_UI/Query/PolyCurves.cs
  Revit_Engine/Query/FamilyTypeFullName.cs
Labels: type:compliance
