Repository BHoM/Revit_Toolkit, pull requests merged in 2020-04, with the labels that each got.

#653 virtual keyword and {get; set;} added to BH.oM.Adapters.Revit.Generic.Map
  Revit_oM/Generic/TypeMap.cs
Labels: type:compliance

#658 Unit converts made robust and informative
  Engine_Revit_UI/Query/BHoMUnitType.cs
Labels: type:bug

#659 CreateNonExsiting enabled
  Adapter_Revit_UI/AdapterActions/Push.cs
Labels: type:feature

#662 Reference to Common_Engine removed
  Engine_Revit_UI/Engine_Revit_UI.csproj
  Engine_Revit_UI/Query/BoundingBox.cs
Labels: type:compliance

#667 Deprecated code base older than 3.0 removed
  Revit_Engine/Create/Elements/Floor.cs
  Revit_Engine/Create/Elements/Roof.cs
  Revit_Engine/Create/Elements/Wall.cs
  Revit_Engine/Revit_Engine.csproj
Labels: type:compliance

#671 CustomData handling cleanup vol. 1
  Adapter_Revit_UI/CRUD/Read.cs
  Adapter_Revit_UI/Modify/SetIdentifiers.cs
  Adapter_Revit_UI/RevitUIAdapter.cs
  Engine_Revit_UI/Compute/Warnings.cs
  Engine_Revit_UI/Convert/Revit/FromRevit/BHoMObject.cs
  Engine_Revit_UI/Convert/Revit/FromRevit/InstanceProperties.cs
  Engine_Revit_UI/Convert/Revit/ToRevit/ViewPlan.cs
  Engine_Revit_UI/Modify/AddAdjacentSpaceId.cs
  Engine_Revit_UI/Modify/AddSpaceId.cs
  Engine_Revit_UI/Modify/SetIdentifiers.cs
  Engine_Revit_UI/Query/WorksetId.cs
  Revit_Adapter/Aliases.cs
  Revit_Adapter/Revit_Adapter.csproj
  Revit_Engine/Create/Elements/BHoMObject.cs
  Revit_Engine/Create/Elements/DraftingInstance.cs
  Revit_Engine/Create/Elements/ModelInstance.cs
  Revit_Engine/Create/Elements/Panel.cs
  Revit_Engine/Create/Elements/Sheet.cs
  Revit_Engine/Create/Elements/ViewPlan.cs
  Revit_Engine/Create/Elements/Viewport.cs
  Revit_Engine/Create/Properties/InstanceProperties.cs
  Revit_Engine/Modify/RemoveIdentifiers.cs
  Revit_Engine/Query/AdjacentSpaceId.cs
  Revit_Engine/Query/CategoryName.cs
  Revit_Engine/Query/Duplicate.cs
  Revit_Engine/Query/Edges.cs
  Revit_Engine/Query/ElementId.cs
  Revit_Engine/Query/Family.cs
  Revit_Engine/Query/FamilyName.cs
  Revit_Engine/Query/FamilyPlacementTypeName.cs
  Revit_Engine/Query/FamilyTypeName.cs
  Revit_Engine/Query/SpaceId.cs
  Revit_Engine/Query/UniqueId.cs
  Revit_Engine/Query/WorksetId.cs
  Revit_Engine/Revit_Engine.csproj
Labels: type:compliance

#683 Removing Deprecated Geometry methods
  Engine_Revit_UI/Query/IsContaining.cs
  Engine_Revit_UI/Query/PolyCurve.cs
Labels: type:external-api-changes
