Repository BHoM/Revit_Toolkit, pull requests merged in 2020-05, with the labels that each got.

#692 Data_oM reference set to copy local = false
  Revit_Engine/Revit_Engine.csproj
Labels: type:compliance

#697 Readme.md updated
  README.md
Labels: type:documentation

#699 Set space location to boundary centroid
  Engine_Revit_UI/Convert/Environment/FromRevit/Space.cs
Labels: type:feature

#704 Update following changes in the oM for PlanarSurface
  Engine_Revit_UI/Convert/Geometry/FromRevit/Surface.cs
  Engine_Revit_UI/Query/PlanarSurfaceDictionary.cs
Labels: type:external-api-changes

#729 RevitTypes method supported with a private dictionary to avoid Reflection overhead
  Engine_Revit_UI/Query/RevitTypes.cs
Labels: type:feature

#733 Add space perimeter to space pull
  Engine_Revit_UI/Convert/Environment/FromRevit/Space.cs
Labels: type:feature

#735 Unbounded room stopped from crashing
  Engine_Revit_UI/Convert/Environment/FromRevit/Space.cs
Labels: type:bug

#731 Handling of LogicalNotRequest implemented
  Engine_Revit_UI/Engine_Revit_UI.csproj
  Engine_Revit_UI/Query/ElementIds/ElementIds.cs
  Engine_Revit_UI/Query/ElementIds/ElementIdsByExclusion.cs
  Revit_Engine/Query/Discipline.cs
Labels: type:feature
