Repository BHoM/Revit_Toolkit, pull requests merged in 2021-07, with the labels that each got.

#1045 Revit_Core_Engine: Add functionality to create reflected ceiling plan
  Revit_Core_Engine/Create/View/ViewReflectedCeilingPlan.cs
  Revit_Core_Engine/Revit_Core_Engine.csproj
Labels: type:feature

#1051 Section update issues resolved
  Revit_Core_Engine/Query/ElementType.cs
Labels: type:bug

#1053 Revit_Core_Engine: Allow custom boundingbox for isometric 3D views
  Revit_Core_Engine/Create/View/View3D.cs
Labels: size:S, type:feature

#1057 Revit_Toolkit: Replace calls to Clone methods with calls to Base DeepClone or ShallowClone
  Revit_Engine/Modify/Transform.cs
Labels: type:compliance
