Repository BHoM/Revit_Toolkit, pull requests merged in 2021-09, with the labels that each got.

#1073 Push of Foundation Slabs enabled
  Revit_Core_Engine/Convert/Physical/ToRevit/Floor.cs
Labels: type:bug

#1080 UI button layout tweaked
  Revit_Core_Adapter/Listener/RevitListener.cs
Labels: type:documentation

#1084 Return type of wire convert aligned
  Revit_Core_Engine/Convert/MEP/FromRevit/Wire.cs
Labels: type:bug

#1088 Create.RevitPullConfig versioned
  Revit_Engine/Create/Config/RevitPullConfig.cs
Labels: type:bug

#1082 Add tolerance parameter for pull with PlanarSurface and IsClosed methods
  Revit_Core_Engine/Convert/Revit/FromRevit/DraftingInstance.cs
  Revit_Core_Engine/Query/AnalyticalOutlines.cs
Labels: type:bug

#1090 OneLevelBased hosted family creation bug fixed
  Revit_Core_Engine/Create/FamilyInstance/FamilyInstance.cs
Labels: type:bug

#1092 ElementTypeNotFoundWarning made more informative
  Revit_Core_Engine/Compute/Warnings.cs
Labels: type:documentation

#1094 Bug in Create.FamilyInstance for one level based, non-hosted families fixed
  Revit_Core_Engine/Create/FamilyInstance/FamilyInstance.cs
Labels: type:bug

#1097 ElementTypeNotFoundWarning made even more informative
  Revit_Core_Engine/Compute/Warnings.cs
Labels: type:documentation

#1098 Revit 2022 added to Readme.md
  README.md
Labels: type:documentation

#1075 Align to Graphics_oM `Vertex` to `RenderPoint` refactoring
  Revit_Core_Engine/Query/RenderMeshes.cs
Labels: type:compliance
