Repository BHoM/Revit_Toolkit, pull requests merged in 2021-12, with the labels that each got.

#1130 Legacy versioning fixed
  Revit_Engine/Versioning_50.json
Labels: type:compliance

#1131 Revit_Engine: aligments and simplifications of the RevitDiffing backend
  Revit_Engine/Compute/RevitDiffing.cs
  Revit_Engine/Query/ComparisonInclusion.cs
  Revit_Engine/Query/HashString.cs
  Revit_Engine/Revit_Engine.csproj
  Revit_Engine/Versioning_50.json
  Revit_oM/Config/RevitComparisonConfig.cs
  Revit_oM/Revit_oM.csproj
Labels: type:feature

#1135 Framing elements stopped from being pushed with wrong length in case of default Start/End Extension param value not equal to zero
  Revit_Core_Engine/Convert/Physical/ToRevit/FamilyInstance.cs
Labels: type:bug

#1137 Dynamo stopped from crashing because of BHoM loading different version of assemblies on startup
  Revit_Core_Adapter/Listener/RevitListener.cs
  Revit_Core_Engine/Compute/LoadSensitiveDynamoAssemblies.cs
  Revit_Core_Engine/Revit_Core_Engine.csproj
Labels: type:bug

#1139 Revit_oM: `RevitComparisonConfig` to inherit from `BaseComparisonConfig`, not `ComparisonConfig`
  Revit_oM/Config/RevitComparisonConfig.cs
Labels: type:compliance

#1143 Reimplement versioning for deleted panel create methods.
  Revit_Engine/Versioning_50.json
Labels: type:compliance

#1141 Query.OpeningSurfaces_Curtain to use Create.PlanarSurface to generate output
  Revit_Core_Engine/Query/OpeningSurface.cs
Labels: type:bug
