Repository BHoM/Revit_Toolkit, pull requests merged in 2022-01, with the labels that each got.

#1160 Aligning with Grid and Level migration to Spatial
  Revit_Core_Engine/Convert/Geometry/FromRevit/Grid.cs
  Revit_Core_Engine/Convert/Geometry/FromRevit/Level.cs
  Revit_Core_Engine/Convert/Geometry/ToRevit/Grid.cs
  Revit_Core_Engine/Convert/Geometry/ToRevit/Level.cs
  Revit_Core_Engine/Convert/ToRevit.cs
  Revit_Core_Engine/Modify/Postprocess.cs
  Revit_Core_Engine/Modify/SetLocation.cs
  Revit_Core_Engine/Query/BHoMType.cs
  Revit_Core_Engine/Query/Level.cs
Labels: type:external-api-changes

#1155 CopyParameters fixed to copy the properties independent of parameters
  Revit_Core_Engine/Modify/CopyParameters.cs
Labels: type:bug

#1164 Align with changes in Structure_Engine
  Revit_Core_Engine/Convert/Structure/FromRevit/Bars.cs
Labels: type:external-api-changes

#1171 CODEOWNERS file removed
  .github/CODEOWNERS
Labels: type:compliance
