Repository BHoM/Revit_Toolkit, pull requests merged in 2023-06, with the labels that each got.

#1360 Add `Query.Parameters`
  Revit_Core_Engine/Query/Parameters.cs
Labels: type:feature

#1370 Invalid workset information stopped from being passed on pull from non-workshared models
  Revit_Core_Engine/Query/Identifiers.cs
Labels: type:bug

#1372 Geometry extraction edge case fixed
  Revit_Core_Engine/Query/GeometryPrimitives.cs
Labels: type:bug

#1379 Documentation issues fixed
  Revit_Engine/Compute/RevitDiffing.cs
Labels: type:documentation
