Repository BHoM/Revit_Toolkit, pull requests merged in 2023-12, with the labels that each got.

#1422 `DoesIntersect` - add intersection between point and element, point and solid, and solid vs solid
  Revit_Core_Engine/Query/DoesIntersect.cs
Labels: type:feature

#1425 Wiki link updated
  Revit_Core_Adapter/Listener/RevitListener.cs
  Revit_Engine/Query/RevitToolkitWiki.cs
Labels: type:documentation

#1426 Create.LineStyle method migrated
  Revit_Core_Engine/Create/Category/LineStyle.cs
Labels: type:compliance
