Repository BHoM/Revit_Toolkit, pull requests merged in 2023-07, with the labels that each got.

#1384 Warnings about nonplanar faces added when querying panel surfaces
  Revit_Core_Engine/Query/PanelPlanes.cs
Labels: type:bug

#1390 Method checking whether an element has a visible parameter
  Revit_Core_Engine/Query/HasVisibleParameter.cs
Labels: type:feature

#1392 Update altConfigs file
  altConfigs.txt
Labels: type:compliance
