Repository BHoM/Revit_Toolkit, pull requests merged in 2024-06, with the labels that each got.

#1480 Elements In Path
  Revit_Core_Engine/Query/ElementsInPath.cs
Labels: type:feature

#1482 DoesIntersect - intersection between solids bug fix
  Revit_Core_Engine/Query/DoesIntersect.cs
Labels: type:bug

#1485 Conformal transformation bug fixed in geometry primitives query
  Revit_Core_Engine/Query/GeometryPrimitives.cs
Labels: type:bug

#1486 Issues with pulling from links fixed
  Revit_Core_Adapter/CRUD/Read.cs
  Revit_Core_Engine/Compute/SplitRequestTreeByLinks.cs
  Revit_Core_Engine/Convert/FromRevit.cs
  Revit_Core_Engine/Modify/Postprocess.cs
Labels: type:bug

#1488 Elements In Path - infinite loop bug fix
  Revit_Core_Engine/Query/ElementsInPath.cs
Labels: type:bug

#1490 Elements In Path - incorrect order bug fix
  Revit_Core_Engine/Query/ElementsInPath.cs
Labels: type:bug

#1491 Update AssemblyFileVersion to 7.3
  Revit_Adapter/Revit_Adapter.csproj
  Revit_Core_Adapter/Revit_Core_Adapter.csproj
  Revit_Core_Engine/Convert/FromRevit.cs
  Revit_Core_Engine/Query/CurtainPanels.cs
  Revit_Core_Engine/Revit_Core_Engine.csproj
  Revit_Core_Engine/Versioning_72.json
  Revit_Engine/Revit_Engine.csproj
  Revit_oM/Revit_oM.csproj
Labels: type:compliance
