Repository BHoM/Revit_Toolkit, pull requests merged in 2024-01, with the labels that each got.

#1433 Update readme link
  README.md
Labels: type:documentation

#1431 'Edited by' added to the default blacklist in diffing
  Revit_oM/Config/RevitComparisonConfig.cs
Labels: type:feature

#1434 Align to Diffing_oM change of Id to ID
  Revit_Engine/Compute/RevitDiffing.cs
Labels: type:compliance

#1438 Removed room/space geometry bug fixed
  Revit_Core_Engine/Query/GeometryPrimitives.cs
Labels: type:bug

#1436 `DoesIntersect` - add bbox check
  Revit_Core_Engine/Query/DoesIntersect.cs
Labels: type:feature
